'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RNT2011.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _01_messages() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("01_messages", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1300719676_gtk_execute() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1300719676_gtk-execute", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1325001816_report_user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1325001816_report_user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1325001859_distributor_report() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1325001859_distributor-report", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1325002196_kdeprint_testprinter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1325002196_kdeprint-testprinter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1325002206_list_error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1325002206_list-error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1328979223_preferences_desktop_cryptography() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1328979223_preferences-desktop-cryptography", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1328979354_gnome_session_logout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1328979354_gnome-session-logout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1328979428_Shutdown_Box_Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1328979428_Shutdown_Box_Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1328979428_Shutdown_Box_Red1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1328979428_Shutdown_Box_Red1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _Exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property align_bellow__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("align_bellow (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property app() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("app", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property app1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("app1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property biaya() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("biaya", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blackboard_drawing__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blackboard_drawing (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calculator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calculator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property checkout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property computer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("computer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property computer__arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("computer--arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property computer1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("computer1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property computer2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("computer2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_revert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document-revert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property documents_email__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("documents_email (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property download_database() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download-database", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_redo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit-redo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property emblem_money() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emblem-money", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_horizontal__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder-horizontal (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property full_time() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("full-time", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property google_web_elements__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("google_web_elements (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gudang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gudang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property import() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("import", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property information__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("information (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property key_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property money_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("money_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property network_local() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("network_local", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property notepad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notepad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property otorisasi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("otorisasi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property restore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("restore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property return_sales() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("return_sales", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property satuan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("satuan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property server_components__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("server_components (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shutdown16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shutdown16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sync() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sync", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property system_users() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("system-users", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property terminPembayran() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("terminPembayran", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property time_admin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("time-admin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user6_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user6_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usermnaager() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usermnaager", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property whatNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("whatNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wilayah() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wilayah", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
