'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports BPRoc_LIB.EntitiesModel


Namespace EntitiesModel	
	
	Public Partial Class AuditTrail

		Private _username As String 
		Public Overridable Property Username As String 
			Get
		        Return Me._username
			End Get
			Set(ByVal value As String)
		        Me._username = value
			End Set
		End Property

		Private _tglInput As Date 
		Public Overridable Property TglInput As Date 
			Get
		        Return Me._tglInput
			End Get
			Set(ByVal value As Date)
		        Me._tglInput = value
			End Set
		End Property

		Private _kdAuditTrail As Integer 
		Public Overridable Property KdAuditTrail As Integer 
			Get
		        Return Me._kdAuditTrail
			End Get
			Set(ByVal value As Integer)
		        Me._kdAuditTrail = value
			End Set
		End Property

		Private _operations As String 
		Public Overridable Property Operations As String 
			Get
		        Return Me._operations
			End Get
			Set(ByVal value As String)
		        Me._operations = value
			End Set
		End Property

		Private _modules As String 
		Public Overridable Property Modules As String 
			Get
		        Return Me._modules
			End Get
			Set(ByVal value As String)
		        Me._modules = value
			End Set
		End Property

		Private _hosts As String 
		Public Overridable Property Hosts As String 
			Get
		        Return Me._hosts
			End Get
			Set(ByVal value As String)
		        Me._hosts = value
			End Set
		End Property

		Private _actions As String 
		Public Overridable Property Actions As String 
			Get
		        Return Me._actions
			End Get
			Set(ByVal value As String)
		        Me._actions = value
			End Set
		End Property

		Private _auditTrailDets As IList(Of AuditTrailDet)  = new List(Of AuditTrailDet)
		Public Overridable ReadOnly Property AuditTrailDets As IList(Of AuditTrailDet) 
			Get
		        Return Me._auditTrailDets
			End Get
		End Property

	End Class
End Namespace
