'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports BPRoc_LIB.EntitiesModel


Namespace EntitiesModel	
	
	Public Partial Class AuditTrailDet

		Private _kdAudit As Integer 
		Public Overridable Property KdAudit As Integer 
			Get
		        Return Me._kdAudit
			End Get
			Set(ByVal value As Integer)
		        Me._kdAudit = value
			End Set
		End Property

		Private _oldValues As String 
		Public Overridable Property OldValues As String 
			Get
		        Return Me._oldValues
			End Get
			Set(ByVal value As String)
		        Me._oldValues = value
			End Set
		End Property

		Private _newValues As String 
		Public Overridable Property NewValues As String 
			Get
		        Return Me._newValues
			End Get
			Set(ByVal value As String)
		        Me._newValues = value
			End Set
		End Property

		Private _fields As String 
		Public Overridable Property Fields As String 
			Get
		        Return Me._fields
			End Get
			Set(ByVal value As String)
		        Me._fields = value
			End Set
		End Property

		Private _auditTrail As AuditTrail 
		Public Overridable Property AuditTrail As AuditTrail 
			Get
		        Return Me._auditTrail
			End Get
			Set(ByVal value As AuditTrail)
		        Me._auditTrail = value
			End Set
		End Property

	End Class
End Namespace
