'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata


Namespace EntitiesModel	
	
	Public Partial Class ErrorLog

		Private _queryText As String 
		Public Overridable Property QueryText As String 
			Get
		        Return Me._queryText
			End Get
			Set(ByVal value As String)
		        Me._queryText = value
			End Set
		End Property

		Private _modulName As String 
		Public Overridable Property ModulName As String 
			Get
		        Return Me._modulName
			End Get
			Set(ByVal value As String)
		        Me._modulName = value
			End Set
		End Property

		Private _iD As Integer 
		Public Overridable Property ID As Integer 
			Get
		        Return Me._iD
			End Get
			Set(ByVal value As Integer)
		        Me._iD = value
			End Set
		End Property

		Private _hostName As String 
		Public Overridable Property HostName As String 
			Get
		        Return Me._hostName
			End Get
			Set(ByVal value As String)
		        Me._hostName = value
			End Set
		End Property

		Private _formName As String 
		Public Overridable Property FormName As String 
			Get
		        Return Me._formName
			End Get
			Set(ByVal value As String)
		        Me._formName = value
			End Set
		End Property

		Private _errorText As String 
		Public Overridable Property ErrorText As String 
			Get
		        Return Me._errorText
			End Get
			Set(ByVal value As String)
		        Me._errorText = value
			End Set
		End Property

	End Class
End Namespace
