'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata


Namespace EntitiesModel	
	
	Public Partial Class HostReg

		Private _descReg As String 
		Public Overridable Property DescReg As String 
			Get
		        Return Me._descReg
			End Get
			Set(ByVal value As String)
		        Me._descReg = value
			End Set
		End Property

		Private _dateReg As String 
		Public Overridable Property DateReg As String 
			Get
		        Return Me._dateReg
			End Get
			Set(ByVal value As String)
		        Me._dateReg = value
			End Set
		End Property

		Private _hostName As String 
		Public Overridable Property HostName As String 
			Get
		        Return Me._hostName
			End Get
			Set(ByVal value As String)
		        Me._hostName = value
			End Set
		End Property

		Private _isStatus As Boolean? 
		Public Overridable Property IsStatus As Boolean? 
			Get
		        Return Me._isStatus
			End Get
			Set(ByVal value As Boolean?)
		        Me._isStatus = value
			End Set
		End Property

	End Class
End Namespace
