'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata


Namespace EntitiesModel	
	
	Public Partial Class Pelanggan

		Private _kdplgn As String 
		Public Overridable Property Kdplgn As String 
			Get
		        Return Me._kdplgn
			End Get
			Set(ByVal value As String)
		        Me._kdplgn = value
			End Set
		End Property

		Private _nmplgn As String 
		Public Overridable Property Nmplgn As String 
			Get
		        Return Me._nmplgn
			End Get
			Set(ByVal value As String)
		        Me._nmplgn = value
			End Set
		End Property

		Private _almtplgn As String 
		Public Overridable Property Almtplgn As String 
			Get
		        Return Me._almtplgn
			End Get
			Set(ByVal value As String)
		        Me._almtplgn = value
			End Set
		End Property

		Private _kotaplgn As String 
		Public Overridable Property Kotaplgn As String 
			Get
		        Return Me._kotaplgn
			End Get
			Set(ByVal value As String)
		        Me._kotaplgn = value
			End Set
		End Property

		Private _telpplgn As String 
		Public Overridable Property Telpplgn As String 
			Get
		        Return Me._telpplgn
			End Get
			Set(ByVal value As String)
		        Me._telpplgn = value
			End Set
		End Property

		Private _faxplgn As String 
		Public Overridable Property Faxplgn As String 
			Get
		        Return Me._faxplgn
			End Get
			Set(ByVal value As String)
		        Me._faxplgn = value
			End Set
		End Property

		Private _hpplgn As String 
		Public Overridable Property Hpplgn As String 
			Get
		        Return Me._hpplgn
			End Get
			Set(ByVal value As String)
		        Me._hpplgn = value
			End Set
		End Property

		Private _isStatus As Boolean 
		Public Overridable Property IsStatus As Boolean 
			Get
		        Return Me._isStatus
			End Get
			Set(ByVal value As Boolean)
		        Me._isStatus = value
			End Set
		End Property

		Private _userName As String 
		Public Overridable Property UserName As String 
			Get
		        Return Me._userName
			End Get
			Set(ByVal value As String)
		        Me._userName = value
			End Set
		End Property

		Private _tglInput As Date 
		Public Overridable Property TglInput As Date 
			Get
		        Return Me._tglInput
			End Get
			Set(ByVal value As Date)
		        Me._tglInput = value
			End Set
		End Property

		Private _tglUpdate As Date 
		Public Overridable Property TglUpdate As Date 
			Get
		        Return Me._tglUpdate
			End Get
			Set(ByVal value As Date)
		        Me._tglUpdate = value
			End Set
		End Property

		Private _formName As String 
		Public Overridable Property FormName As String 
			Get
		        Return Me._formName
			End Get
			Set(ByVal value As String)
		        Me._formName = value
			End Set
		End Property

	End Class
End Namespace
