'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports BPRoc_LIB.EntitiesModel


Namespace EntitiesModel	
	
	Public Partial Class PenjualanDet

		Private _kdFakturPenj As String 
		Public Overridable Property KdFakturPenj As String 
			Get
		        Return Me._kdFakturPenj
			End Get
			Set(ByVal value As String)
		        Me._kdFakturPenj = value
			End Set
		End Property

		Private _kdBarang As String 
		Public Overridable Property KdBarang As String 
			Get
		        Return Me._kdBarang
			End Get
			Set(ByVal value As String)
		        Me._kdBarang = value
			End Set
		End Property

		Private _qty As Integer 
		Public Overridable Property Qty As Integer 
			Get
		        Return Me._qty
			End Get
			Set(ByVal value As Integer)
		        Me._qty = value
			End Set
		End Property

		Private _total As Decimal 
		Public Overridable Property Total As Decimal 
			Get
		        Return Me._total
			End Get
			Set(ByVal value As Decimal)
		        Me._total = value
			End Set
		End Property

		Private _isStatus As Boolean 
		Public Overridable Property IsStatus As Boolean 
			Get
		        Return Me._isStatus
			End Get
			Set(ByVal value As Boolean)
		        Me._isStatus = value
			End Set
		End Property

		Private _nama As String 
		Public Overridable Property Nama As String 
			Get
		        Return Me._nama
			End Get
			Set(ByVal value As String)
		        Me._nama = value
			End Set
		End Property

		Private _kdsatuan As String 
		Public Overridable Property Kdsatuan As String 
			Get
		        Return Me._kdsatuan
			End Get
			Set(ByVal value As String)
		        Me._kdsatuan = value
			End Set
		End Property

		Private _hargaJual As Decimal 
		Public Overridable Property HargaJual As Decimal 
			Get
		        Return Me._hargaJual
			End Get
			Set(ByVal value As Decimal)
		        Me._hargaJual = value
			End Set
		End Property

		Private _hargaBeli As Decimal 
		Public Overridable Property HargaBeli As Decimal 
			Get
		        Return Me._hargaBeli
			End Get
			Set(ByVal value As Decimal)
		        Me._hargaBeli = value
			End Set
		End Property

		Private _username As String 
		Public Overridable Property Username As String 
			Get
		        Return Me._username
			End Get
			Set(ByVal value As String)
		        Me._username = value
			End Set
		End Property

		Private _tglUpdate As Date 
		Public Overridable Property TglUpdate As Date 
			Get
		        Return Me._tglUpdate
			End Get
			Set(ByVal value As Date)
		        Me._tglUpdate = value
			End Set
		End Property

		Private _tglInput As Date 
		Public Overridable Property TglInput As Date 
			Get
		        Return Me._tglInput
			End Get
			Set(ByVal value As Date)
		        Me._tglInput = value
			End Set
		End Property

		Private _formName As String 
		Public Overridable Property FormName As String 
			Get
		        Return Me._formName
			End Get
			Set(ByVal value As String)
		        Me._formName = value
			End Set
		End Property

		Private _nomor As Short 
		Public Overridable Property nomor As Short 
			Get
		        Return Me._nomor
			End Get
			Set(ByVal value As Short)
		        Me._nomor = value
			End Set
		End Property

		Private _penjualan As Penjualan 
		Public Overridable Property Penjualan As Penjualan 
			Get
		        Return Me._penjualan
			End Get
			Set(ByVal value As Penjualan)
		        Me._penjualan = value
			End Set
		End Property

	End Class
End Namespace
