'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports BPRoc_LIB.EntitiesModel


Namespace EntitiesModel	
	
	Public Partial Class Penjualan

		Private _kdFakturPenj As String 
		Public Overridable Property KdFakturPenj As String 
			Get
		        Return Me._kdFakturPenj
			End Get
			Set(ByVal value As String)
		        Me._kdFakturPenj = value
			End Set
		End Property

		Private _tglJual As Date 
		Public Overridable Property TglJual As Date 
			Get
		        Return Me._tglJual
			End Get
			Set(ByVal value As Date)
		        Me._tglJual = value
			End Set
		End Property

		Private _jam As Date 
		Public Overridable Property Jam As Date 
			Get
		        Return Me._jam
			End Get
			Set(ByVal value As Date)
		        Me._jam = value
			End Set
		End Property

		Private _totalBayar As Decimal 
		Public Overridable Property TotalBayar As Decimal 
			Get
		        Return Me._totalBayar
			End Get
			Set(ByVal value As Decimal)
		        Me._totalBayar = value
			End Set
		End Property

		Private _userName As String 
		Public Overridable Property UserName As String 
			Get
		        Return Me._userName
			End Get
			Set(ByVal value As String)
		        Me._userName = value
			End Set
		End Property

		Private _tglInput As Date 
		Public Overridable Property TglInput As Date 
			Get
		        Return Me._tglInput
			End Get
			Set(ByVal value As Date)
		        Me._tglInput = value
			End Set
		End Property

		Private _tglUpdate As Date 
		Public Overridable Property TglUpdate As Date 
			Get
		        Return Me._tglUpdate
			End Get
			Set(ByVal value As Date)
		        Me._tglUpdate = value
			End Set
		End Property

		Private _formName As String 
		Public Overridable Property FormName As String 
			Get
		        Return Me._formName
			End Get
			Set(ByVal value As String)
		        Me._formName = value
			End Set
		End Property

		Private _isStatus As Boolean 
		Public Overridable Property IsStatus As Boolean 
			Get
		        Return Me._isStatus
			End Get
			Set(ByVal value As Boolean)
		        Me._isStatus = value
			End Set
		End Property

		Private _customer As String 
		Public Overridable Property Customer As String 
			Get
		        Return Me._customer
			End Get
			Set(ByVal value As String)
		        Me._customer = value
			End Set
		End Property

		Private _penjualanDets As IList(Of PenjualanDet)  = new List(Of PenjualanDet)
		Public Overridable ReadOnly Property PenjualanDets As IList(Of PenjualanDet) 
			Get
		        Return Me._penjualanDets
			End Get
		End Property

	End Class
End Namespace
