'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports BPRoc_LIB.EntitiesModel


Namespace EntitiesModel	
	
	Public Partial Class SatuanDet

		Private _kdbarang As String 
		Public Overridable Property Kdbarang As String 
			Get
		        Return Me._kdbarang
			End Get
			Set(ByVal value As String)
		        Me._kdbarang = value
			End Set
		End Property

		Private _par As Integer 
		Public Overridable Property Par As Integer 
			Get
		        Return Me._par
			End Get
			Set(ByVal value As Integer)
		        Me._par = value
			End Set
		End Property

		Private _hargaJual As Decimal 
		Public Overridable Property HargaJual As Decimal 
			Get
		        Return Me._hargaJual
			End Get
			Set(ByVal value As Decimal)
		        Me._hargaJual = value
			End Set
		End Property

		Private _hargaBeli As Decimal 
		Public Overridable Property HargaBeli As Decimal 
			Get
		        Return Me._hargaBeli
			End Get
			Set(ByVal value As Decimal)
		        Me._hargaBeli = value
			End Set
		End Property

		Private _isStatus As Boolean 
		Public Overridable Property IsStatus As Boolean 
			Get
		        Return Me._isStatus
			End Get
			Set(ByVal value As Boolean)
		        Me._isStatus = value
			End Set
		End Property

		Private _barcode As String 
		Public Overridable Property Barcode As String 
			Get
		        Return Me._barcode
			End Get
			Set(ByVal value As String)
		        Me._barcode = value
			End Set
		End Property

		Private _username As String 
		Public Overridable Property Username As String 
			Get
		        Return Me._username
			End Get
			Set(ByVal value As String)
		        Me._username = value
			End Set
		End Property

		Private _formName As String 
		Public Overridable Property FormName As String 
			Get
		        Return Me._formName
			End Get
			Set(ByVal value As String)
		        Me._formName = value
			End Set
		End Property

		Private _tglInput As Date 
		Public Overridable Property TglInput As Date 
			Get
		        Return Me._tglInput
			End Get
			Set(ByVal value As Date)
		        Me._tglInput = value
			End Set
		End Property

		Private _tglUpdate As Date 
		Public Overridable Property TglUpdate As Date 
			Get
		        Return Me._tglUpdate
			End Get
			Set(ByVal value As Date)
		        Me._tglUpdate = value
			End Set
		End Property

		Private _kdSatuan As String 
		Public Overridable Property KdSatuan As String 
			Get
		        Return Me._kdSatuan
			End Get
			Set(ByVal value As String)
		        Me._kdSatuan = value
			End Set
		End Property

		Private _barang As Barang 
		Public Overridable Property Barang As Barang 
			Get
		        Return Me._barang
			End Get
			Set(ByVal value As Barang)
		        Me._barang = value
			End Set
		End Property

	End Class
End Namespace
