'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata


Namespace EntitiesModel	
	
	Public Partial Class T_Owner

		Private _nama As String 
		Public Overridable Property Nama As String 
			Get
		        Return Me._nama
			End Get
			Set(ByVal value As String)
		        Me._nama = value
			End Set
		End Property

		Private _alamat As String 
		Public Overridable Property Alamat As String 
			Get
		        Return Me._alamat
			End Get
			Set(ByVal value As String)
		        Me._alamat = value
			End Set
		End Property

		Private _telepon As String 
		Public Overridable Property Telepon As String 
			Get
		        Return Me._telepon
			End Get
			Set(ByVal value As String)
		        Me._telepon = value
			End Set
		End Property

		Private _mobile As String 
		Public Overridable Property Mobile As String 
			Get
		        Return Me._mobile
			End Get
			Set(ByVal value As String)
		        Me._mobile = value
			End Set
		End Property

		Private _fax As String 
		Public Overridable Property Fax As String 
			Get
		        Return Me._fax
			End Get
			Set(ByVal value As String)
		        Me._fax = value
			End Set
		End Property

		Private _eMail As String 
		Public Overridable Property EMail As String 
			Get
		        Return Me._eMail
			End Get
			Set(ByVal value As String)
		        Me._eMail = value
			End Set
		End Property

		Private _noRegister As String 
		Public Overridable Property NoRegister As String 
			Get
		        Return Me._noRegister
			End Get
			Set(ByVal value As String)
		        Me._noRegister = value
			End Set
		End Property

		Private _userName As String 
		Public Overridable Property UserName As String 
			Get
		        Return Me._userName
			End Get
			Set(ByVal value As String)
		        Me._userName = value
			End Set
		End Property

		Private _tglInput As Date? 
		Public Overridable Property TglInput As Date? 
			Get
		        Return Me._tglInput
			End Get
			Set(ByVal value As Date?)
		        Me._tglInput = value
			End Set
		End Property

		Private _tglUpdate As Date? 
		Public Overridable Property TglUpdate As Date? 
			Get
		        Return Me._tglUpdate
			End Get
			Set(ByVal value As Date?)
		        Me._tglUpdate = value
			End Set
		End Property

		Private _isStatus As Boolean? 
		Public Overridable Property IsStatus As Boolean? 
			Get
		        Return Me._isStatus
			End Get
			Set(ByVal value As Boolean?)
		        Me._isStatus = value
			End Set
		End Property

		Private _namaToko As String 
		Public Overridable Property NamaToko As String 
			Get
		        Return Me._namaToko
			End Get
			Set(ByVal value As String)
		        Me._namaToko = value
			End Set
		End Property

	End Class
End Namespace
