'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata


Namespace EntitiesModel	
	
	Public Partial Class T_Setting

		Private _tValue As String 
		Public Overridable Property TValue As String 
			Get
		        Return Me._tValue
			End Get
			Set(ByVal value As String)
		        Me._tValue = value
			End Set
		End Property

		Private _tname As String 
		Public Overridable Property Tname As String 
			Get
		        Return Me._tname
			End Get
			Set(ByVal value As String)
		        Me._tname = value
			End Set
		End Property

	End Class
End Namespace
