'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata


Namespace EntitiesModel	
	
	Public Partial Class Vw_laporanPenjualan

		Private _userName As String 
		Public Overridable Property UserName As String 
			Get
		        Return Me._userName
			End Get
			Set(ByVal value As String)
		        Me._userName = value
			End Set
		End Property

		Private _total As Decimal? 
		Public Overridable Property Total As Decimal? 
			Get
		        Return Me._total
			End Get
			Set(ByVal value As Decimal?)
		        Me._total = value
			End Set
		End Property

		Private _tglJual As Date 
		Public Overridable Property TglJual As Date 
			Get
		        Return Me._tglJual
			End Get
			Set(ByVal value As Date)
		        Me._tglJual = value
			End Set
		End Property

		Private _qty As Integer? 
		Public Overridable Property Qty As Integer? 
			Get
		        Return Me._qty
			End Get
			Set(ByVal value As Integer?)
		        Me._qty = value
			End Set
		End Property

		Private _nama As String 
		Public Overridable Property Nama As String 
			Get
		        Return Me._nama
			End Get
			Set(ByVal value As String)
		        Me._nama = value
			End Set
		End Property

		Private _laba As Decimal? 
		Public Overridable Property Laba As Decimal? 
			Get
		        Return Me._laba
			End Get
			Set(ByVal value As Decimal?)
		        Me._laba = value
			End Set
		End Property

		Private _kdsatuan As String 
		Public Overridable Property Kdsatuan As String 
			Get
		        Return Me._kdsatuan
			End Get
			Set(ByVal value As String)
		        Me._kdsatuan = value
			End Set
		End Property

		Private _kdFakturPenj As String 
		Public Overridable Property KdFakturPenj As String 
			Get
		        Return Me._kdFakturPenj
			End Get
			Set(ByVal value As String)
		        Me._kdFakturPenj = value
			End Set
		End Property

		Private _hargaJual As Decimal? 
		Public Overridable Property HargaJual As Decimal? 
			Get
		        Return Me._hargaJual
			End Get
			Set(ByVal value As Decimal?)
		        Me._hargaJual = value
			End Set
		End Property

		Private _customer As String 
		Public Overridable Property Customer As String 
			Get
		        Return Me._customer
			End Get
			Set(ByVal value As String)
		        Me._customer = value
			End Set
		End Property

	End Class
End Namespace
