'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports BPRoc_LIB.EntitiesModel


Namespace EntitiesModel	
	Public Partial Class POSModel
		 Inherits OpenAccessContext
		Private Shared connectionStringName As String = "MandiriConnection"
		
		Private Shared backend As BackendConfiguration = GetBackendConfiguration()
		
		Private Shared metadataSource As MetadataSource = XmlMetadataSource.FromAssemblyResource("Model.rlinq")
	
		Public Sub New()
			MyBase.New(connectionStringName, backend, metadataSource)
		End Sub
		
		Public Sub New(ByVal connection As String)
			MyBase.New(connection, backend, metadataSource)
		End Sub
		
		Public Sub New(ByVal backendConfiguration As BackendConfiguration)
			MyBase.New(connectionStringName, backendConfiguration, metadataSource)
		End Sub
			
		Public Sub New(ByVal connection As String, ByVal metadataSource As MetadataSource)
			MyBase.New(connection, backend, metadataSource)
		End Sub
			
		Public Sub New(ByVal connection As String, ByVal backendConfiguration As BackendConfiguration, ByVal metadataSource As MetadataSource)
			MyBase.New(connection, backendConfiguration, metadataSource)
		End Sub
			
		Public ReadOnly Property T_Users() As  IQueryable(Of T_User)
	    	Get
				Return Me.GetAll(Of T_User)()
	    	End Get
		End Property
		
		Public ReadOnly Property T_Owners() As  IQueryable(Of T_Owner)
	    	Get
				Return Me.GetAll(Of T_Owner)()
	    	End Get
		End Property
		
		Public ReadOnly Property Suppliers() As  IQueryable(Of Supplier)
	    	Get
				Return Me.GetAll(Of Supplier)()
	    	End Get
		End Property
		
		Public ReadOnly Property SatuanDets() As  IQueryable(Of SatuanDet)
	    	Get
				Return Me.GetAll(Of SatuanDet)()
	    	End Get
		End Property
		
		Public ReadOnly Property Satuans() As  IQueryable(Of Satuan)
	    	Get
				Return Me.GetAll(Of Satuan)()
	    	End Get
		End Property
		
		Public ReadOnly Property PenjualanDets() As  IQueryable(Of PenjualanDet)
	    	Get
				Return Me.GetAll(Of PenjualanDet)()
	    	End Get
		End Property
		
		Public ReadOnly Property Penjualans() As  IQueryable(Of Penjualan)
	    	Get
				Return Me.GetAll(Of Penjualan)()
	    	End Get
		End Property
		
		Public ReadOnly Property Pelanggans() As  IQueryable(Of Pelanggan)
	    	Get
				Return Me.GetAll(Of Pelanggan)()
	    	End Get
		End Property
		
		Public ReadOnly Property Kategoris() As  IQueryable(Of Kategori)
	    	Get
				Return Me.GetAll(Of Kategori)()
	    	End Get
		End Property
		
		Public ReadOnly Property Biayas() As  IQueryable(Of Biaya)
	    	Get
				Return Me.GetAll(Of Biaya)()
	    	End Get
		End Property
		
		Public ReadOnly Property Barangs() As  IQueryable(Of Barang)
	    	Get
				Return Me.GetAll(Of Barang)()
	    	End Get
		End Property
		
		Public ReadOnly Property Vw_laporanPenjualans() As  IQueryable(Of Vw_laporanPenjualan)
	    	Get
				Return Me.GetAll(Of Vw_laporanPenjualan)()
	    	End Get
		End Property
		
		Public ReadOnly Property AuditTrailDets() As  IQueryable(Of AuditTrailDet)
	    	Get
				Return Me.GetAll(Of AuditTrailDet)()
	    	End Get
		End Property
		
		Public ReadOnly Property AuditTrails() As  IQueryable(Of AuditTrail)
	    	Get
				Return Me.GetAll(Of AuditTrail)()
	    	End Get
		End Property
		
		Public ReadOnly Property HostRegs() As  IQueryable(Of HostReg)
	    	Get
				Return Me.GetAll(Of HostReg)()
	    	End Get
		End Property
		
		Public ReadOnly Property Vw_LaporanBarangs() As  IQueryable(Of Vw_LaporanBarang)
	    	Get
				Return Me.GetAll(Of Vw_LaporanBarang)()
	    	End Get
		End Property
		
		Public ReadOnly Property T_Settings() As  IQueryable(Of T_Setting)
	    	Get
				Return Me.GetAll(Of T_Setting)()
	    	End Get
		End Property
		
		Public ReadOnly Property ErrorLogs() As  IQueryable(Of ErrorLog)
	    	Get
				Return Me.GetAll(Of ErrorLog)()
	    	End Get
		End Property
		
		Public Shared Function GetBackendConfiguration() As BackendConfiguration
			Dim backend As BackendConfiguration = New BackendConfiguration()
			backend.Backend = "mssql"
			backend.ProviderName = "System.Data.SqlClient"
			Return backend
		End Function
	End Class
End Namespace

